# Generated by Django 4.2.1 on 2023-05-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('posx', models.IntegerField()),
                ('posy', models.IntegerField()),
                ('place', models.CharField(max_length=50)),
                ('extImg', models.CharField(max_length=50)),
                ('intImg', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decoration', models.CharField(max_length=50)),
                ('posx', models.IntegerField()),
                ('posy', models.IntegerField()),
                ('place', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('ground', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.CharField(max_length=50)),
                ('posx', models.IntegerField()),
                ('posy', models.IntegerField()),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
