# Generated by Django 4.2.1 on 2023-05-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineApp', '0004_place_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='creds',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
