# Generated by Django 4.2.1 on 2023-05-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineApp', '0008_place_extsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(max_length=50)),
                ('texture', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
                ('posx', models.FloatField()),
                ('posy', models.FloatField()),
                ('toPosx', models.FloatField()),
                ('toPosy', models.FloatField()),
                ('toPlace', models.FloatField()),
                ('extSize', models.FloatField()),
                ('place', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='extSize',
        ),
    ]
