# Generated by Django 4.2.1 on 2023-05-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('posx', models.IntegerField()),
                ('posy', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('imgup', models.CharField(max_length=50)),
                ('imgdown', models.CharField(max_length=50)),
                ('imgright', models.CharField(max_length=50)),
                ('imgleft', models.CharField(max_length=50)),
                ('animup', models.CharField(max_length=50)),
                ('animdown', models.CharField(max_length=50)),
                ('animleft', models.CharField(max_length=50)),
                ('animright', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
            ],
        ),
    ]
