# Generated by Django 4.2.1 on 2023-05-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineApp', '0003_alter_building_posx_alter_building_posy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='log',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
