# Generated by Django 4.2.1 on 2023-05-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineApp', '0005_player_creds'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.AddField(
            model_name='place',
            name='building',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='owner',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='posx',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='posy',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
