# Generated by Django 4.2.1 on 2023-05-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineApp', '0006_delete_building_place_building_place_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='building',
            new_name='texture',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='ground',
            new_name='txtExt',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='img',
            new_name='texture',
        ),
        migrations.AddField(
            model_name='decoration',
            name='texture',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='water',
            name='texture',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
