# Generated by Django 4.2.1 on 2023-05-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineApp', '0007_rename_building_place_texture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='extSize',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
