# Generated by Django 4.2.1 on 2023-05-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineApp', '0009_portal_remove_place_extsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portal',
            name='toPlace',
            field=models.CharField(max_length=50),
        ),
    ]
